### PR TITLE
Fixed cancel for fallback

### LINKED ISSUE #3: .cancel() fallback for request fallback
clear the timeout

### PR DESCRIPTION
**Pull request by tarqd**
Fixes #3

### CODE REVIEW

**Comment by blakeembrey** [comment]
@jonathanong Can we publish the latest version to npm?

**Comment by jonathanong** [comment]
negative, don't have npm rights

**Comment by blakeembrey** [comment]
Who does? /cc @visionmedia

**Comment by tj** [comment]
published

**Pull request merged**
